/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import conexion.ConexionBD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUAN MANUEL
 */
public class OrdenarModelo extends javax.swing.JPanel {

    /**
     * Creates new form OrdenarModelo
     */
    public OrdenarModelo() {
        initComponents();
        Ordenar();
    }
   public void Ordenar(){
        DefaultTableModel modelo = (DefaultTableModel)Ordenar.getModel();
        modelo.setRowCount(0);
         ConexionBD cc = new ConexionBD(); //creo clase conxeion base de datos
        Connection cn = cc.getConnection();//creo variable para iniciar la conexion
        PreparedStatement pst = null;  // sirve para hacer los llamados de la base
        String sql ="SELECT id_modelo,nombre_marca,caballos_fuerzaModelo,nombre_modelo FROM modelo,marca WHERE modelo.id_marca=marca.id_marca ORDER BY nombre_marca  ";
        
        try {
            
         pst=cn.prepareStatement(sql);
          ResultSet rs = pst.executeQuery();
          while(rs.next()){
              Vector v =new Vector();
              v.add(rs.getInt(1));
              v.add(rs.getString(2));
               v.add(rs.getString(3));
                  v.add(rs.getString(4));
               
               modelo.addRow(v);
               Ordenar.setModel(modelo);
              
              
          }
              
             
        
    }catch(SQLException e){
    
}
    }
              
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Ordenar = new javax.swing.JTable();

        Ordenar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Marca", "Caballos de fuerza", "Modelo"
            }
        ));
        jScrollPane1.setViewportView(Ordenar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ordenar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
