/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import classDAO.concesionarioDAO;
import classDAO.marcaDAO;
import classVO.concesionarioVO;
import classVO.marcaVO;

/**
 *
 * @author JUAN MANUEL
 */
public class ProgramaFRM extends javax.swing.JFrame {

    /**
     * Creates new form ProgramaFRM
     */
    public ProgramaFRM() {
        initComponents();
   
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        registrar_marca = new javax.swing.JButton();
        actualizar_provedor = new javax.swing.JButton();
        buscar_marca = new javax.swing.JButton();
        eliminar_concesionario = new javax.swing.JButton();
        limpiar_marca = new javax.swing.JButton();
        estado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        id_marca = new javax.swing.JLabel();
        marcasss = new javax.swing.JLabel();
        fiel = new javax.swing.JLabel();
        IDM = new javax.swing.JTextField();
        marcaM = new javax.swing.JTextField();
        LimpiarM = new javax.swing.JButton();
        EliminarM = new javax.swing.JButton();
        BuscarM = new javax.swing.JButton();
        actualizarM = new javax.swing.JButton();
        registrarM = new javax.swing.JButton();
        estadoM = new javax.swing.JTextField();
        concesionarioM = new javax.swing.JTextField();
        Lista_concesionario = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("ID");

        jLabel5.setText("Nombre concesionario");

        jLabel6.setText("Direccion");

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        registrar_marca.setText("Registrar");
        registrar_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_marcaActionPerformed(evt);
            }
        });

        actualizar_provedor.setText("Actualizar");
        actualizar_provedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizar_provedorActionPerformed(evt);
            }
        });

        buscar_marca.setText("Buscar");
        buscar_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscar_marcaActionPerformed(evt);
            }
        });

        eliminar_concesionario.setText("Eliminar");
        eliminar_concesionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_concesionarioActionPerformed(evt);
            }
        });

        limpiar_marca.setText("Limpiar ");
        limpiar_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar_marcaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel1.setText("Informacion Concesionario");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(185, 185, 185))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(estado)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(registrar_marca)
                        .addGap(44, 44, 44)
                        .addComponent(actualizar_provedor)
                        .addGap(50, 50, 50)
                        .addComponent(buscar_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(eliminar_concesionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                        .addComponent(limpiar_marca))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID)
                            .addComponent(direccion)
                            .addComponent(Nombre))))
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrar_marca)
                    .addComponent(actualizar_provedor)
                    .addComponent(buscar_marca)
                    .addComponent(eliminar_concesionario)
                    .addComponent(limpiar_marca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Concesionario", jPanel3);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setText("Informacion Marca");

        id_marca.setText("ID");

        marcasss.setText("Marca");

        fiel.setText(" Concesionario");

        IDM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDMActionPerformed(evt);
            }
        });

        LimpiarM.setText("Limpiar");
        LimpiarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarMActionPerformed(evt);
            }
        });

        EliminarM.setText("Eliminar");
        EliminarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarMActionPerformed(evt);
            }
        });

        BuscarM.setText("Buscar");
        BuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarMActionPerformed(evt);
            }
        });

        actualizarM.setText("Actualizar");
        actualizarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarMActionPerformed(evt);
            }
        });

        registrarM.setText("Registrar");
        registrarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMActionPerformed(evt);
            }
        });

        estadoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoMActionPerformed(evt);
            }
        });

        concesionarioM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                concesionarioMActionPerformed(evt);
            }
        });

        Lista_concesionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lista_concesionarioActionPerformed(evt);
            }
        });

        jLabel3.setText("ID concesionario");

        jLabel7.setText("(opcioal)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marcasss)
                            .addComponent(id_marca)
                            .addComponent(registrarM))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDM))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(actualizarM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                .addComponent(BuscarM)
                                .addGap(63, 63, 63)
                                .addComponent(EliminarM)
                                .addGap(97, 97, 97)
                                .addComponent(LimpiarM)
                                .addGap(37, 37, 37))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(7, 7, 7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(fiel))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jLabel7)))
                                .addGap(19, 19, 19)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(marcaM, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Lista_concesionario, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(concesionarioM, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(estadoM, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_marca)
                    .addComponent(IDM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marcasss)
                    .addComponent(marcaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lista_concesionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiel))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(concesionarioM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarM)
                    .addComponent(actualizarM)
                    .addComponent(EliminarM)
                    .addComponent(BuscarM)
                    .addComponent(LimpiarM))
                .addGap(37, 37, 37)
                .addComponent(estadoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jTabbedPane1.addTab("Marca", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void registrar_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_marcaActionPerformed
      concesionarioVO concesionario = new concesionarioVO();
      concesionario.setId_concesionario(Integer.parseInt(ID.getText()));
      concesionario.setDireccion_concesionario(direccion.getText());
      concesionario.setNombre_concesionario((Nombre.getText()));
 
      
      String resp= concesionarioDAO.registrarconcesionarios(concesionario);
      estado.setText(resp);
      ID.setText("");
      direccion.setText("");
      Nombre.setText("");
     
      //cargar concesionarios
      
      
      
      
      
        
        
    }//GEN-LAST:event_registrar_marcaActionPerformed

    private void eliminar_concesionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_concesionarioActionPerformed
        // TODO add your handling code here:
        
        String resp = concesionarioDAO.eliminarconcesionarios(ID.getText());
        estado.setText(resp);
        ID.setText("");
        direccion.setText("");
        Nombre.setText("");
        
    }//GEN-LAST:event_eliminar_concesionarioActionPerformed

    private void actualizar_provedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizar_provedorActionPerformed
      concesionarioVO concesionario = new concesionarioVO();
      
      concesionario.setId_concesionario(Integer.parseInt(ID.getText()));
      concesionario.setDireccion_concesionario(direccion.getText());
      concesionario.setNombre_concesionario((Nombre.getText()));
 
      
      String resp= concesionarioDAO.actualizarconcesionarios(concesionario);
      estado.setText(resp);
      ID.setText("");
      direccion.setText("");
      Nombre.setText("");
     
      //cargar concesionarios
    }//GEN-LAST:event_actualizar_provedorActionPerformed

    private void buscar_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscar_marcaActionPerformed
        // TODO add your handling code here:
        
        concesionarioVO concesionario  =concesionarioDAO.buscarconcesionarios(ID.getText());
        ID.setText(concesionario.getId_concesionario()+"");
        Nombre.setText(concesionario.getNombre_concesionario());
        direccion.setText(concesionario.getDireccion_concesionario());
        estado.setText(concesionario.getResultado());
        
        
    }//GEN-LAST:event_buscar_marcaActionPerformed

    private void limpiar_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar_marcaActionPerformed
        // TODO add your handling code here:
        ID.setText("");
        direccion.setText("");
        Nombre.setText("");
     
    }//GEN-LAST:event_limpiar_marcaActionPerformed

    private void IDMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDMActionPerformed

    private void registrarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMActionPerformed
     
      marcaVO marca = new marcaVO();
      marca.setId_marca(Integer.parseInt(IDM.getText())); 
      marca.setNombre_marca(marcaM.getText());
      marca.setId_concesionario(Integer.parseInt(concesionarioM.getText()));
 
      
      String resp= marcaDAO.registrarmarcas(marca);
      estadoM.setText(resp);
      IDM.setText("");
      marcaM.setText("");
      concesionarioM.setText("");
        
    }//GEN-LAST:event_registrarMActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void actualizarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarMActionPerformed
        // TODO add your handling code here:
        
             marcaVO marca = new marcaVO();
      
      marca.setId_marca(Integer.parseInt(IDM.getText()));
      marca.setNombre_marca(marcaM.getText());
       marca.setId_concesionario(Integer.parseInt(concesionarioM.getText()));
 
      
      String resp= marcaDAO.actualizarmarcas(marca);
      estado.setText(resp);
      IDM.setText("");
      concesionarioM.setText("");
      marcaM.setText("");
     
   
    }//GEN-LAST:event_actualizarMActionPerformed

    private void BuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarMActionPerformed
        // TODO add your handling code here:
        
         marcaVO marca  = marcaDAO.buscarmarcas(IDM.getText());
        IDM.setText(marca.getId_marca()+"");
        marcaM.setText(marca.getNombre_marca());
        concesionarioM.setText(marca.getId_concesionario()+"");
        estado.setText(marca.getResultado());
        
        
        
    }//GEN-LAST:event_BuscarMActionPerformed

    private void EliminarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarMActionPerformed
String resp = marcaDAO.eliminarmarcas(IDM.getText());
        estadoM.setText(resp);
        IDM.setText("");
        marcaM.setText("");
       concesionarioM.setText("");
         
       
         
       
  
        
    }//GEN-LAST:event_EliminarMActionPerformed

    private void LimpiarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarMActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_LimpiarMActionPerformed

    private void estadoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoMActionPerformed

    private void concesionarioMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_concesionarioMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_concesionarioMActionPerformed

    private void Lista_concesionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lista_concesionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lista_concesionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramaFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramaFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramaFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramaFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramaFRM().setVisible(true);
            }

        });  
    }
/*
    public  void cargaconcesionarios(int busca){
        int index = 1;
        Lista_concesionarios.removeAll();
        Lista_concesionarios.addItem("seleciona un concesionario");
        for(concesionarioVO conce: concesionarioDAO.getListconcesionario()){
            Lista_concesionarios.addItem(conce);
            if(conce.getId_concesionario() == busca){
              Lista_concesionarios.setSelectedIndex(index);
            }
            index++;
        }
        
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarM;
    private javax.swing.JButton EliminarM;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField IDM;
    private javax.swing.JButton LimpiarM;
    private javax.swing.JComboBox Lista_concesionario;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton actualizarM;
    private javax.swing.JButton actualizar_provedor;
    private javax.swing.JButton buscar_marca;
    private javax.swing.JTextField concesionarioM;
    private javax.swing.JTextField direccion;
    private javax.swing.JButton eliminar_concesionario;
    private javax.swing.JTextField estado;
    private javax.swing.JTextField estadoM;
    private javax.swing.JLabel fiel;
    private javax.swing.JLabel id_marca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton limpiar_marca;
    private javax.swing.JTextField marcaM;
    private javax.swing.JLabel marcasss;
    private javax.swing.JButton registrarM;
    private javax.swing.JButton registrar_marca;
    // End of variables declaration//GEN-END:variables
}
